<a href="https://colab.research.google.com/github/DigoShane/GitHub-ML/blob/main/00_pytorch_Fundamentals_ZTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

#Converting this into a text cell using Cmd+MM

In [75]:
print("Hello Im excited to learn Pytorch! ")

Hello Im excited to learn Pytorch! 


In [76]:
!nvidia-smi #This is to get GPU info

/bin/bash: line 1: nvidia-smi: command not found


In [77]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
#cu128 is cuda version 12.8

2.11.0+cpu


##Introduction to Tensors

Created using torch.Tensor() = https://docs.pytorch.org/docs/2.12/tensors.html

In [78]:
# Creating a scalar const storing 7
scalar = torch.tensor(7)
scalar

tensor(7)

In [79]:
#checking the dimension
scalar.ndim

0

In [80]:
#get tensor back as python int
scalar.item()

7

In [81]:
#Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape) #2x1 vector so shape is 2.

tensor([7, 7])
1
torch.Size([2])


In [82]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [83]:
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX[-1])#one from the end. SHORT HAND

tensor([7, 8])
tensor([ 9, 10])
tensor([ 9, 10])


In [84]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape) # 1 3x3 shaped tensor.

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [85]:
print(TENSOR[0])
print(TENSOR[0][0])
print(TENSOR[0][1])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([1, 2, 3])
tensor([3, 6, 9])


In [86]:
#RANDOM TENSORS
#these are used to update weights and biases?

#Std tandom tensor
Random_tensor = torch.rand(3,4)
print(Random_tensor)
print(Random_tensor.ndim)
print(Random_tensor.shape)

#Using random generator
g = torch.Generator().manual_seed(42)
c = torch.rand(2, 3, generator=g)
print("c =", c)

# Output to an existing tensor
out_tensor = torch.empty(2, 3)
torch.rand(2, 3, out=out_tensor)
print("out_tensor =", out_tensor)

# Enable autograd
d = torch.rand(2, 3, requires_grad=True)
print("d =", d)

tensor([[0.8345, 0.3561, 0.6459, 0.8258],
        [0.5081, 0.2669, 0.9324, 0.8343],
        [0.4483, 0.3520, 0.9210, 0.6556]])
2
torch.Size([3, 4])
c = tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
out_tensor = tensor([[0.7351, 0.1700, 0.0191],
        [0.1919, 0.8672, 0.0732]])
d = tensor([[0.7571, 0.5000, 0.3613],
        [0.0148, 0.7369, 0.0979]], requires_grad=True)


In [87]:
#Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channel (r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [88]:
# Zeros and ones
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
print(zeros)
print(ones)
print(zeros*Random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [89]:
#determine the data type
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [90]:
# Use torch.range()
one_to_ten = torch.arange(start = 0, end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##TENSOR DataType

In [92]:
#Float 32 tensor is the default datatype
float_32_Tensor = torch.tensor([3.0,6.0,9.0], dtype=None, #default is f32
                                              device=None,
                                              requires_grad=False)
float_32_Tensor

tensor([3., 6., 9.])

In [93]:
float_32_Tensor.dtype

torch.float32

### TENSOR datatypes
**Note:** Tensor datatypes is one of the 3 big errors with Pytorch and deep learning:
1. Tensors not right datatype (randomly changing precision can cause erors) -> use 'tensor.dtype'
2. Tensors not right shape (for tensor multiplication) -> use 'tensor.shape'
3. Tensors not on the right device (either CPU or GPU) -> use 'tensor.device'

In [94]:
#converting float 32 to float 16
float_16_tensor = float_32_Tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [95]:
#multiplying f32 x f16
ans = float_16_tensor*float_32_Tensor
ans, ans.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [96]:
#int32xfloat32
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
ans = int_32_tensor*float_32_Tensor
ans, ans.dtype # converts to float 32.

(tensor([ 9., 36., 81.]), torch.float32)

#size is a function and shape is an attribute.
#attributes vs fns, the latter are written with shape.

### MAnipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element wise)
* Division
* Matrix multiplication
* Dot product


In [97]:
# Create a tensor
tensor = torch.tensor([1,2,3])
print(tensor + 10) #addition
print(tensor * 10) #multiplication
print(tensor - 10) #subtraction

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [98]:
#Trying out inbuilt functions of pytorch.
print(torch.add(tensor, 10)) #addition
print(torch.mul(tensor, 10)) #multiplication
print(torch.sub(tensor, 10)) #subtraction

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [99]:
# MAtrix multiplication
tensor * tensor
torch.matmul(tensor, tensor)

tensor(14)

In [105]:
#using @ for Matmul
print(tensor @ tensor)

tensor(14)


In [100]:
#Lets us time matrix multiplication using For look and internal method.
#internal methods are faster cause the multiplication would require us to retrieve things first.
# dont use print. The print makes it take double the time.
%%time
value = 0
for i in tensor:
  value += i*i
value

CPU times: user 556 µs, sys: 0 ns, total: 556 µs
Wall time: 594 µs


tensor(14)

In [101]:
#Note when using it dont use print. The print also takes up time.
%%time
torch.matmul(tensor, tensor)

CPU times: user 503 µs, sys: 0 ns, total: 503 µs
Wall time: 1.34 ms


tensor(14)

In [110]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

#using mm for matmul. It needs 2D
print(torch.mm(tensor_A,tensor_B.T))
print(tensor_B.T) # Note that .T is transpose.

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


## TENSOR AGGREGATION

Find min, max, mean, sum, etc

In [124]:
x = torch.tensor([1, -2, 4, 5,-10, 3, 5])
print(x.dtype)

#find min
print(torch.min(x), x.min())

#find max
print(torch.max(x), x.max())

#find mean
#print(torch.mean(x)) #gives error as it requires tensor of float32.
print(torch.mean(x.type(torch.float32)), x.type(torch.float32).mean())

#find sum
print(torch.sum(x), x.sum())

torch.int64
tensor(-10) tensor(-10)
tensor(5) tensor(5)
tensor(0.8571) tensor(0.8571)
tensor(6) tensor(6)


In [125]:
#Argmin and arg max
torch.argmin(x), x.argmin()

(tensor(4), tensor(4))

In [127]:
#argmax
torch.argmax(x), x.argmax() #return the first occurance of max.

(tensor(3), tensor(3))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keeps the memory as the original tensor
* Stacking - combines multiple tensors of different types.
            vstack for stacking vertically and hstack for stacking size by side. Think concatenate.
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor.cdouble
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [134]:
import torch
x = torch.arange(0,10,1)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [136]:
# Add an extra dimension
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape #Notice the extra bracket

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Size([2, 5]))

In [137]:
# Change view
z = x.view(2,5)
z, z.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Size([2, 5]))

In [139]:
#If i change z, x changes. View of a tensor shares the same memory as the original tensor.
z[:, 0] = 5
z, x

(tensor([[5, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
#Stacking tensors
x_stacked = torch.stack([x,x,x,x], dim=0)
print(x_stacked)
x_stacked = torch.stack([x,x,x,x], dim=1)
print(x_