<a href="https://colab.research.google.com/github/DigoShane/GitHub-ML/blob/main/00_pytorch_Fundamentals_ZTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

#Converting this into a text cell using Cmd+MM

In [1]:
print("Hello Im excited to learn Pytorch! ")

Hello Im excited to learn Pytorch! 


In [2]:
!nvidia-smi #This is to get GPU info

Mon Jun 22 00:21:22 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   57C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
#cu128 is cuda version 12.8

2.11.0+cu128


##Introduction to Tensors

Created using torch.Tensor() = https://docs.pytorch.org/docs/2.12/tensors.html

In [4]:
# Creating a scalar const storing 7
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#checking the dimension
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape) #2x1 vector so shape is 2.

tensor([7, 7])
1
torch.Size([2])


In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [9]:
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX[-1])#one from the end. SHORT HAND

tensor([7, 8])
tensor([ 9, 10])
tensor([ 9, 10])


In [10]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape) # 1 3x3 shaped tensor.

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [11]:
print(TENSOR[0])
print(TENSOR[0][0])
print(TENSOR[0][1])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([1, 2, 3])
tensor([3, 6, 9])


In [12]:
#RANDOM TENSORS
#these are used to update weights and biases?

#Std tandom tensor
Random_tensor = torch.rand(3,4)
print(Random_tensor)
print(Random_tensor.ndim)
print(Random_tensor.shape)

#Using random generator
g = torch.Generator().manual_seed(42)
c = torch.rand(2, 3, generator=g)
print("c =", c)

# Output to an existing tensor
out_tensor = torch.empty(2, 3)
torch.rand(2, 3, out=out_tensor)
print("out_tensor =", out_tensor)

# Enable autograd
d = torch.rand(2, 3, requires_grad=True)
print("d =", d)

tensor([[0.2050, 0.5837, 0.4429, 0.1438],
        [0.2409, 0.5475, 0.7353, 0.7645],
        [0.3422, 0.5869, 0.2704, 0.3709]])
2
torch.Size([3, 4])
c = tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
out_tensor = tensor([[0.5781, 0.7713, 0.2366],
        [0.4206, 0.0065, 0.9111]])
d = tensor([[0.1074, 0.7500, 0.8494],
        [0.6899, 0.5090, 0.5642]], requires_grad=True)


In [13]:
#Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channel (r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [14]:
# Zeros and ones
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
print(zeros)
print(ones)
print(zeros*Random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [15]:
#determine the data type
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [16]:
# Use torch.range()
one_to_ten = torch.arange(start = 0, end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##TENSOR DataType

In [18]:
#Float 32 tensor is the default datatype
float_32_Tensor = torch.tensor([3.0,6.0,9.0], dtype=None, #default is f32
                                              device=None,
                                              requires_grad=False)
float_32_Tensor

tensor([3., 6., 9.])

In [19]:
float_32_Tensor.dtype

torch.float32

### TENSOR datatypes
**Note:** Tensor datatypes is one of the 3 big errors with Pytorch and deep learning:
1. Tensors not right datatype (randomly changing precision can cause erors) -> use 'tensor.dtype'
2. Tensors not right shape (for tensor multiplication) -> use 'tensor.shape'
3. Tensors not on the right device (either CPU or GPU) -> use 'tensor.device'

In [20]:
#converting float 32 to float 16
float_16_tensor = float_32_Tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [21]:
#multiplying f32 x f16
ans = float_16_tensor*float_32_Tensor
ans, ans.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [22]:
#int32xfloat32
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
ans = int_32_tensor*float_32_Tensor
ans, ans.dtype # converts to float 32.

(tensor([ 9., 36., 81.]), torch.float32)

#size is a function and shape is an attribute.
#attributes vs fns, the latter are written with shape.

### MAnipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element wise)
* Division
* Matrix multiplication
* Dot product


In [23]:
# Create a tensor
tensor = torch.tensor([1,2,3])
print(tensor + 10) #addition
print(tensor * 10) #multiplication
print(tensor - 10) #subtraction

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [24]:
#Trying out inbuilt functions of pytorch.
print(torch.add(tensor, 10)) #addition
print(torch.mul(tensor, 10)) #multiplication
print(torch.sub(tensor, 10)) #subtraction

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])


In [25]:
# MAtrix multiplication
tensor * tensor
torch.matmul(tensor, tensor)

tensor(14)

In [26]:
#using @ for Matmul
print(tensor @ tensor)

tensor(14)


In [27]:
#Lets us time matrix multiplication using For look and internal method.
#internal methods are faster cause the multiplication would require us to retrieve things first.
# dont use print. The print makes it take double the time.
%%time
value = 0
for i in tensor:
  value += i*i
value

CPU times: user 883 µs, sys: 0 ns, total: 883 µs
Wall time: 2.09 ms


tensor(14)

In [28]:
#Note when using it dont use print. The print also takes up time.
%%time
torch.matmul(tensor, tensor)

CPU times: user 308 µs, sys: 54 µs, total: 362 µs
Wall time: 442 µs


tensor(14)

In [29]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

#using mm for matmul. It needs 2D
print(torch.mm(tensor_A,tensor_B.T))
print(tensor_B.T) # Note that .T is transpose.

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


## TENSOR AGGREGATION

Find min, max, mean, sum, etc

In [30]:
x = torch.tensor([1, -2, 4, 5,-10, 3, 5])
print(x.dtype)

#find min
print(torch.min(x), x.min())

#find max
print(torch.max(x), x.max())

#find mean
#print(torch.mean(x)) #gives error as it requires tensor of float32.
print(torch.mean(x.type(torch.float32)), x.type(torch.float32).mean())

#find sum
print(torch.sum(x), x.sum())

torch.int64
tensor(-10) tensor(-10)
tensor(5) tensor(5)
tensor(0.8571) tensor(0.8571)
tensor(6) tensor(6)


In [31]:
#Argmin and arg max
torch.argmin(x), x.argmin()

(tensor(4), tensor(4))

In [32]:
#argmax
torch.argmax(x), x.argmax() #return the first occurance of max.

(tensor(3), tensor(3))

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keeps the memory as the original tensor
* Stacking - combines multiple tensors of different types.
            vstack for stacking vertically and hstack for stacking size by side. Think concatenate.
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor.cdouble
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [33]:
import torch
x = torch.arange(0,10,1)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [34]:
# Add an extra dimension
x_reshaped = x.reshape(1,10)
x_reshaped, x_reshaped.shape #Notice the extra bracket

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [35]:
# Change view
z = x.view(2,5)
z, z.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Size([2, 5]))

In [36]:
#If i change z, x changes. View of a tensor shares the same memory as the original tensor.
#Even though the shape does change, the data stored changes.
z[:, 0] = 5
z, x

(tensor([[5, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [37]:
#Stacking tensors
x_stacked = torch.stack([x,x,x,x], dim=0)
print(x_stacked)
x_stacked = torch.stack([x,x,x,x], dim=1)
print(x_stacked)

tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[5, 5, 5, 5],
        [1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])


In [38]:
#Squeeze and unsqueeze
print(f"previous version")
print(x_reshaped)
print(x_reshaped.shape)
print(f"="*30)
print(f"Squeezed version")
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)
print(x_squeezed.shape) # see 1 bracket less.

previous version
tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
Squeezed version
tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])


In [39]:
# unsqueeze
print(f"Squeezed version of out tensor")
print(x_squeezed)
print(x_squeezed.shape)
print(f"="*30)
print(f"Unsqueezed version")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)
print(x_unsqueezed.shape) # adde extra brackets [a] becomes [[a]]
print(f"="*30)
print(f"Unsqueezed version for dim = 1")
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed)
print(x_unsqueezed.shape) # adde extra brackets to the 1st dimension. [a] becomes [ax1]

Squeezed version of out tensor
tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])
Unsqueezed version
tensor([[5, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
Unsqueezed version for dim = 1
tensor([[5],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([10, 1])


In [40]:
#permute
x_original = torch.rand(size=(224,224,3)) # [h, w, c_c]
x_permuted = x_original.permute(2,0,1) # rearrange to [c_c, h, w]
x_permuted.shape

torch.Size([3, 224, 224])

In [41]:
#BEcause permutation is a view, changing the view, changes the original.
#Moreover, changing the original changes the view.
x_original[0,0,0] = 728218
x_permuted[0,0,0], x_original[0,0,0]

(tensor(728218.), tensor(728218.))

## INDEXING (select data from tensors)

Indexing with pytorch is similar to indexing in numpy

In [42]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [43]:
#index on the 1st dim
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [44]:
#index on the middle bracket
x[0][0] # equiv to x[0,0]

tensor([1, 2, 3])

In [45]:
#index on the last dim
x[0][0][0]

tensor(1)

In [46]:
# to get 9
x[0][2][2]

tensor(9)

In [47]:
# use : to select all of a target dimension.
x[:,0]

tensor([[1, 2, 3]])

In [48]:
x[:,:,1]

tensor([[2, 5, 8]])

## Pytorch Tensors and numpy

Pytorch has funcitonality to interact wiht it.

* Data in numpy, want in pytorch tensor ->  `torch.from_numpy(ndarray)`
* Pytorch tensor to numpy -> `torch.Tensor.numpy()`

##IMP
* default dtype in numpy if f64, contrast with pytorch which is f32.
* Moreover, they don't share memory. Thus changing one does not affect the other.

In [49]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor # numpy's default dtype is f64

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [50]:
tensor =  torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [51]:
numpy_tensor.dtype

dtype('float32')



```
# This is formatted as code
```

## Moving tensors form CPU to GPU

In [56]:
import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device) # by default tensors created on cpu

cuda
tensor([1, 2, 3]) cpu


In [58]:
# move tensor to GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu # the index of the gpu is also returned

tensor([1, 2, 3], device='cuda:0')

NUMPY can only be applied to tensors on **CPU** not on **GPU**

In [60]:
# move tensors to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## EXERCISE

In [78]:
import torch
seed = 0
torch.manual_seed(seed)
rand1 = torch.rand([7,7])
rand1

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [84]:
torch.manual_seed(seed)
rand2 = torch.rand([1,7])
rand2.T

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

In [85]:
rand1 @ rand2.T

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [89]:
seed = 1234
torch.manual_seed(seed)

device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [93]:
tensor = tensor_A @ tensor_B.T
tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [96]:
tensor.max(), tensor.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [97]:
tensor.argmax(), tensor.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [104]:
tens = torch.rand([1,1,1,10])
tens, tens.size()

(tensor([[[[0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839, 0.8083,
            0.7528, 0.8988]]]]),
 torch.Size([1, 1, 1, 10]))

In [103]:
tens.squeeze(), tens.squeeze().size()

(tensor([0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108,
         0.0014]),
 torch.Size([10]))