<a href="https://colab.research.google.com/github/DigoShane/GitHub-ML/blob/main/00_pytorch_Fundamentals_ZTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

#Converting this into a text cell using Cmd+MM

In [1]:
print("Hello Im excited to learn Pytorch! ")

Hello Im excited to learn Pytorch! 


In [2]:
!nvidia-smi #This is to get GPU info

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
#cu128 is cuda version 12.8

2.11.0+cpu


##Introduction to Tensors

Created using torch.Tensor() = https://docs.pytorch.org/docs/2.12/tensors.html

In [4]:
# Creating a scalar const storing 7
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
#checking the dimension
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#Vector
vector = torch.tensor([7,7])
print(vector)
print(vector.ndim)
print(vector.shape) #2x1 vector so shape is 2.

tensor([7, 7])
1
torch.Size([2])


In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [9]:
print(MATRIX[0])
print(MATRIX[1])
print(MATRIX[-1])#one from the end. SHORT HAND

tensor([7, 8])
tensor([ 9, 10])
tensor([ 9, 10])


In [10]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape) # 1 3x3 shaped tensor.

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [11]:
print(TENSOR[0])
print(TENSOR[0][0])
print(TENSOR[0][1])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
tensor([1, 2, 3])
tensor([3, 6, 9])


In [22]:
#RANDOM TENSORS
#these are used to update weights and biases?

#Std tandom tensor
Random_tensor = torch.rand(3,4)
print(Random_tensor)
print(Random_tensor.ndim)
print(Random_tensor.shape)

#Using random generator
g = torch.Generator().manual_seed(42)
c = torch.rand(2, 3, generator=g)
print("c =", c)

# Output to an existing tensor
out_tensor = torch.empty(2, 3)
torch.rand(2, 3, out=out_tensor)
print("out_tensor =", out_tensor)

# Enable autograd
d = torch.rand(2, 3, requires_grad=True)
print("d =", d)

tensor([[0.1074, 0.4447, 0.1874, 0.2848],
        [0.5954, 0.4355, 0.9587, 0.6676],
        [0.5449, 0.7530, 0.3618, 0.4384]])
2
torch.Size([3, 4])
c = tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
out_tensor = tensor([[0.2086, 0.3390, 0.3187],
        [0.0663, 0.4021, 0.0199]])
d = tensor([[0.6433, 0.1803, 0.5729],
        [0.4261, 0.1584, 0.5940]], requires_grad=True)


In [27]:
#Creating a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, color channel (r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [29]:
# Zeros and ones
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
print(zeros)
print(ones)
print(zeros*Random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [30]:
#determine the data type
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [35]:
# Use torch.range()
one_to_ten = torch.arange(start = 0, end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##TENSOR DataType

In [48]:
#Float 32 tensor is the default datatype
float_32_Tensor = torch.tensor([3.0,6.0,9.0], dtype=None, #default is f32
                                              device=None,
                                              requires_grad=False)
float_32_Tensor

tensor([3., 6., 9.])

In [49]:
float_32_Tensor.dtype

torch.float32

### TENSOR datatypes
**Note:** Tensor datatypes is one of the 3 big errors with Pytorch and deep learning:
1. Tensors not right datatype (randomly changing precision can cause erors) -> use 'tensor.dtype'
2. Tensors not right shape (for tensor multiplication) -> use 'tensor.shape'
3. Tensors not on the right device (either CPU or GPU) -> use 'tensor.device'

In [56]:
#converting float 32 to float 16
float_16_tensor = float_32_Tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [57]:
#multiplying f32 x f16
ans = float_16_tensor*float_32_Tensor
ans, ans.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [58]:
#int32xfloat32
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
ans = int_32_tensor*float_32_Tensor
ans, ans.dtype # converts to float 32.

(tensor([ 9., 36., 81.]), torch.float32)

#size is a function and shape is an attribute.
#attributes vs fns, the latter are written with shape.

### MAnipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element wise)
* Division
* Matrix multiplication
* Dot product


In [60]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [61]:
tensor*10

tensor([10, 20, 30])